### ISSUE TITLE
Descendants not determined correctly

### ISSUE THREAD

**Issue by BenPortner** [erikbrinkman/d3-dag#36] opened 2020-05-15 17:12 UTC
Hi @erikbrinkman!

A user filed a [bug](https://github.com/BenPortner/js_family_tree/issues/2) in js_family_tree, which uses d3-dag for display. After digging down, I realized that in his particular case, the dag does not return the correct number of descendants. I prepared a minimum working example, which reproduces the bug:

```html
<!DOCTYPE html>
<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.15.0/d3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-dag@0.3.4/dist/d3-dag.min.js"></script>
    <script>
        links = [
            ["id1", "id3"],
            // ["id2", "id3"],
            ["id3", "id4"],
        ]
        dag = d3.dagConnect()(links);
        nodes = dag.descendants();
        root = nodes.find(n => n.id == "id3");
        dag.children = [root];
        children_of_root = dag.descendants(); // expected: id3, id4, returned: id1, id3, id4
    </script>
</body>
</html>
```

Interestingly, the error does not occur, if `id3`has another parent (you can test this by uncommenting the link). 

I know it seems a bit weird to use `dag.descendants` here instead of `root.descendants` but that's because it is a minimum example. In the working code, have to get the descendants of the whole dag because I am expecting multiple root nodes.

Cheers,
Ben

**Comment by erikbrinkman** [comment] 2020-05-17 03:04
The problem is the trick that d3_dag does to allow for dags with multiple source nodes, as is the case when you uncomment the extra line. In this case, d3_dag inserts a shadow node that represents "the whole dag", with it's children being all of the heads. That special node has an undefined id, representing the fact that it's not a node. All of the functions know to teat that node as special and not return it or process it in most of the functions.

However, in keeping this project in line with d3_hierarchy, each node also functions as a dag as if it were the root, thus, if a dag happens to only have one source node it just returns that node without the special node at the top.

I don't believe this behavior is actually documented anywhere, so I imagine it can be confusing, and *I'm going to leave this open as reminder to actually put better documentation in.*

However, I realize there is a still some bug in the way you're using it, perhaps I help debug or modify what you're doing to fix this problem? If you're tweaking the dag, as you do in the example, a quick solution is probably just to set `dag.id = undefined`. I tried this on your example, and it has the expected / desired results.

Thanks for submitting such a detailed report. I hope this helps!

**Comment by BenPortner** [comment] 2020-05-21 15:34
Hi @erikbrinkman,

> a quick solution is probably just to set dag.id = undefined

That was a quick fix indeed! I did as you suggested and everything seems to work fine now. I'll let you know if I get any other feedback from the user. 

Thank you very much for you time and keep up the amazing work 😃 

Ben

**Comment by BenPortner** [comment] 2020-05-28 19:36
Short update: Because my node hierarchy is effectively hard-coded in a file, overwriting the node id resulted in some problems. To make `descendants()` work without overwriting the id, I decided to insert a shadow node manually like so:

```js
        if(dag.id !=undefined){
            root = dag.copy();
            root.id = undefined;
            root.children = [dag];
            dag = root;
        }
```

Hope it helps other users who experience the same problem!

**Comment by erikbrinkman** [comment] 2020-09-19 17:25
This seems resolved / the issue seems to have stemmed from mutation of the dag, rather than actual error with descendants. I'm going to close this, but feel free to reopen if you have issues.

**Closed by erikbrinkman** 2020-09-19 17:25 UTC
